In [1]:
import numpy as np            # 数値計算
import scipy  as sp              # 数学・科学技術計算

# 確率の考え方

In [2]:
np.random.choice(np.arange(1,7),10)

array([4, 2, 4, 5, 4, 4, 2, 4, 2, 3])

In [3]:
np.random.choice(np.arange(1,7),5,replace=False)  # 非復元抽出

array([6, 2, 4, 1, 5])

In [4]:
np.random.choice(np.arange(1,7),5)                # 復元抽出

array([5, 6, 2, 3, 4])

In [5]:
p = np.array([1,1,1,3,3,3]); p = p/np.sum(p)
np.random.choice(np.arange(1,7),10, p=p)

array([6, 4, 4, 2, 2, 3, 1, 6, 4, 4])

# 期待値と分散

In [6]:
x = np.random.normal(1,2,100)     # 期待値1，標準偏差2の正規分布にしたがうデータを100個生成   
x.mean()                          # データの平均値を計算．np.mean(x) と同じ

0.75321528941748694

In [7]:
x.std()                           # データの標準偏差を計算．np.std(x) と同じ

2.0129158910468172

In [8]:
np.mean(np.abs(x-np.mean(x)) <= np.std(x))    # |x-E[x]]| ≦ sd(x) となるデータの割合

0.67000000000000004

In [9]:
np.mean(np.abs(x-np.mean(x)) <= 2*np.std(x))  # |x-E[x]]| ≦ 2*sd(x) となるデータの割合

0.95999999999999996

# 分位点

In [10]:
from scipy.stats import norm    # sp.stats.normを使う
sp.stats.norm.ppf(0.7)               # N(0,1)の 0.7点

0.52440051270804067

In [11]:
sp.stats.norm.ppf(0.7,loc=1,scale=2) # N(1,2**2)の 0.7点

2.0488010254160813

In [12]:
alpha = 0.05
sp.stats.norm.ppf(1-alpha) # N(0,1)の上側0.05点

1.6448536269514722

# 共分散・相関係数

In [13]:
from sklearn.datasets import load_iris
iris = load_iris()
iris.data.shape            # データ数150, 次元4 

(150, 4)

In [14]:
np.cov(iris.data.T)        # 分散共分散行列(データ行列の転置を入れる)

array([[ 0.68569351, -0.03926846,  1.27368233,  0.5169038 ],
       [-0.03926846,  0.18800403, -0.32171275, -0.11798121],
       [ 1.27368233, -0.32171275,  3.11317942,  1.29638747],
       [ 0.5169038 , -0.11798121,  1.29638747,  0.58241432]])

In [15]:
np.corrcoef(iris.data.T)   # 相関係数行列(データ行列の転置を入れる)

array([[ 1.        , -0.10936925,  0.87175416,  0.81795363],
       [-0.10936925,  1.        , -0.4205161 , -0.35654409],
       [ 0.87175416, -0.4205161 ,  1.        ,  0.9627571 ],
       [ 0.81795363, -0.35654409,  0.9627571 ,  1.        ]])